### ISSUE TITLE
You have requested a non-existent parameter "redis_session_dsn"

### ISSUE THREAD

**Issue by achristodoulou** [composer/packagist#565]
I have installed packagist and did all the configuration and then start php built-in server. When I tried to browse I received the following error. 

I find out that instead of setting up this parameter for redis **redis_dsn: redis://localhost/1** I set the following and it worked **redis_session_dsn: redis://localhost/1**

```

[Fri Aug 14 21:35:50 2015] 127.0.0.1:59212 [500]: /app.php - Uncaught exception 'Symfony\Component\DependencyInjection\Exception\ParameterNotFoundException' with message 'You have requested a non-existent parameter "redis_session_dsn".' in /home/me/Projects/test/packagist/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/ParameterBag.php:106
Stack trace:
#0 /home/me/Projects/test/packagist/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/ParameterBag.php(232): Symfony\Component\DependencyInjection\ParameterBag\ParameterBag->get('redis_session_d...')
#1 /home/me/Projects/test/packagist/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/ParameterBag.php(203): Symfony\Component\DependencyInjection\ParameterBag\ParameterBag->resolveString('%redis_session_...', Array)
#2 /home/me/Projects/test/packagist/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/ParameterBag.php(193): Symfony\Component\DependencyInjection\Para in /home/me/Projects/test/packagist/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/ParameterBag.php on line 106
```

**Comment by achristodoulou** [comment]
Parameter redis_dsn is still required and cannot be removed, otherwise you will receive the following error:

```
21:58 $ app/console assets:install web
                                                                                                 
  [Symfony\Component\DependencyInjection\Exception\ParameterNotFoundException]                   
  You have requested a non-existent parameter "redis_dsn". Did you mean this: "redis_dsn_test"?
```

**Comment by alcohol** [comment]
That is weird, `redis_session_dsn` is defined in defaults.yml, which is included by config.yml, from which prod and dev (and subsequently test) inherit.

**Comment by alcohol** [comment]
I think either a default should be added in defaults.yml, or it should be added to parameters.yml.dist so users will explictly assign it a value when going through this file.

Which solution would you favor, or otherwise what alternative do you suggest, @Seldaek ?
