### ISSUE TITLE
Once I submit a package, 500 Internal Server Error in profile

### ISSUE THREAD

**Issue by nicecp** [composer/packagist#799]
I hava installed packagist in my mac10.11 with php5.6 mysql5.7.15 and solr3.6, submit/view/search/ packages or change password are ok,but once I tab `profile` or `my packages` something goes wrong with infomations like that.

> The server returned a "500 Internal Server Error".

Such `profile` error.
Stack:

> [2017-07-12 06:38:30] request.INFO: Matched route "fos_user_profile_show". {"route_parameters":{"_controller":"Packagist\\WebBundle\\Controller\\UserController::myProfileAction","_route":"fos_user_profile_show"},"request_uri":"http://localhost:3533/profile/"} []
[2017-07-12 06:38:30] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2017-07-12 06:38:30] security.DEBUG: User was reloaded from a user provider. {"username":"chenpeng","provider":"Packagist\\WebBundle\\Security\\Provider\\UserProvider"} []
[2017-07-12 06:38:30] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\DriverException: "An exception occurred while executing 'SELECT DISTINCT id_0 FROM (SELECT p0_.id AS id_0, p0_.name AS name_1, p0_.type AS type_2, p0_.description AS description_3, p0_.language AS language_4, p0_.readme AS readme_5, p0_.github_stars AS github_stars_6, p0_.github_watches AS github_watches_7, p0_.github_forks AS github_forks_8, p0_.github_open_issues AS github_open_issues_9, p0_.repository AS repository_10, p0_.createdAt AS createdAt_11, p0_.updatedAt AS updatedAt_12, p0_.crawledAt AS crawledAt_13, p0_.indexedAt AS indexedAt_14, p0_.dumpedAt AS dumpedAt_15, p0_.autoUpdated AS autoUpdated_16, p0_.abandoned AS abandoned_17, p0_.replacementPackage AS replacementPackage_18, p0_.updateFailureNotified AS updateFailureNotified_19, f1_.id AS id_20 FROM package p0_ LEFT JOIN maintainers_packages m2_ ON p0_.id = m2_.package_id LEFT JOIN fos_user f1_ ON f1_.id = m2_.user_id WHERE f1_.id IN (?)) dctrn_result ORDER BY abandoned_17 ASC, name_1 ASC LIMIT 15 OFFSET 0' with params [1]:

> SQLSTATE[HY000]: General error: 3065 Expression #1 of ORDER BY clause is not in SELECT list, references column 'dctrn_result.abandoned_17' which is not in SELECT list; this is incompatible with DISTINCT" at /Users/cp/code/github/packagist/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 115 {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred while executing 'SELECT DISTINCT id_0 FROM (SELECT p0_.id AS id_0, p0_.name AS name_1, p0_.type AS type_2, p0_.description AS description_3, p0_.language AS language_4, p0_.readme AS readme_5, p0_.github_stars AS github_stars_6, p0_.github_watches AS github_watches_7, p0_.github_forks AS github_forks_8, p0_.github_open_issues AS github_open_issues_9, p0_.repository AS repository_10, p0_.createdAt AS createdAt_11, p0_.updatedAt AS updatedAt_12, p0_.crawledAt AS crawledAt_13, p0_.indexedAt AS indexedAt_14, p0_.dumpedAt AS dumpedAt_15, p0_.autoUpdated AS autoUpdated_16, p0_.abandoned AS abandoned_17, p0_.replacementPackage AS replacementPackage_18, p0_.updateFailureNotified AS updateFailureNotified_19, f1_.id AS id_20 FROM package p0_ LEFT JOIN maintainers_packages m2_ ON p0_.id = m2_.package_id LEFT JOIN fos_user f1_ ON f1_.id = m2_.user_id WHERE f1_.id IN (?)) dctrn_result ORDER BY abandoned_17 ASC, name_1 ASC LIMIT 15 OFFSET 0' with params [1]:

> SQLSTATE[HY000]: General error: 3065 Expression #1 of ORDER BY clause is not in SELECT list, references column 'dctrn_result.abandoned_17' which is not in SELECT list; this is incompatible with DISTINCT at /Users/cp/code/github/packagist/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:115, Doctrine\\DBAL\\Driver\\PDOException(code: HY000): SQLSTATE[HY000]: General error: 3065 Expression #1 of ORDER BY clause is not in SELECT list, references column 'dctrn_result.abandoned_17' which is not in SELECT list; this is incompatible with DISTINCT at /Users/cp/code/github/packagist/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:93, PDOException(code: HY000): SQLSTATE[HY000]: General error: 3065 Expression #1 of ORDER BY clause is not in SELECT list, references column 'dctrn_result.abandoned_17' which is not in SELECT list; this is incompatible with DISTINCT at /Users/cp/code/github/packagist/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91)
[stacktrace]
#0 /Users/cp/code/github/packagist/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(128): Doctrine\\DBAL\\Driver\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\DBAL\\Driver\\PDOException))
#1 /Users/cp/code/github/packagist/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(855): Doctrine\\DBAL\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\DBAL\\Driver\\PDOMySql\\Driver), Object(Doctrine\\DBAL\\Driver\\PDOException), 'SELECT DISTINCT...', Array)
#2 /Users/cp/code/github/packagist/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Exec/SingleSelectExecutor.php(50): Doctrine\\DBAL\\Connection->executeQuery('SELECT DISTINCT...', Array, Array, NULL)
#3 /Users/cp/code/github/packagist/vendor/doctrine/orm/lib/Doctrine/ORM/Query.php(321): Doctrine\\ORM\\Query\\Exec\\SingleSelectExecutor->execute(Object(Doctrine\\DBAL\\Connection), Array, Array)
#4 /Users/cp/code/github/packagist/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php(969): Doctrine\\ORM\\Query->_doExecute()
#5 /Users/cp/code/github/packagist/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php(924): Doctrine\\ORM\\AbstractQuery->executeIgnoreQueryCache(NULL, 3)
#6 /Users/cp/code/github/packagist/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php(751): Doctrine\\ORM\\AbstractQuery->execute(NULL, 3)
#7 /Users/cp/code/github/packagist/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/Pagination/Paginator.php(151): Doctrine\\ORM\\AbstractQuery->getScalarResult()
#8 /Users/cp/code/github/packagist/vendor/pagerfanta/pagerfanta/src/Pagerfanta/Adapter/DoctrineORMAdapter.php(79): Doctrine\\ORM\\Tools\\Pagination\\Paginator->getIterator()
#9 /Users/cp/code/github/packagist/vendor/pagerfanta/pagerfanta/src/Pagerfanta/Pagerfanta.php(319): Pagerfanta\\Adapter\\DoctrineORMAdapter->getSlice(0, 15)
#10 /Users/cp/code/github/packagist/vendor/pagerfanta/pagerfanta/src/Pagerfanta/Pagerfanta.php(303): Pagerfanta\\Pagerfanta->getCurrentPageResultsFromAdapter()
#11 /Users/cp/code/github/packagist/vendor/pagerfanta/pagerfanta/src/Pagerfanta/Pagerfanta.php(475): Pagerfanta\\Pagerfanta->getCurrentPageResults()
#12 /Users/cp/code/github/packagist/src/Packagist/WebBundle/Controller/Controller.php(39): Pagerfanta\\Pagerfanta->getIterator()
#13 /Users/cp/code/github/packagist/src/Packagist/WebBundle/Controller/UserController.php(68): Packagist\\WebBundle\\Controller\\Controller->getPackagesMetadata(Object(Pagerfanta\\Pagerfanta))
#14 [internal function]: Packagist\\WebBundle\\Controller\\UserController->myProfileAction(Object(Symfony\\Component\\HttpFoundation\\Request))
#15 /Users/cp/code/github/packagist/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(144): call_user_func_array(Array, Array)
#16 /Users/cp/code/github/packagist/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(64): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw(Object(Symfony\\Component\\HttpFoundation\\Request), 1)
#17 /Users/cp/code/github/packagist/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/DependencyInjection/ContainerAwareHttpKernel.php(69): Symfony\\Component\\HttpKernel\\HttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#18 /Users/cp/code/github/packagist/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(185): Symfony\\Component\\HttpKernel\\DependencyInjection\\ContainerAwareHttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#19 /Users/cp/code/github/packagist/web/app.php(25): Symfony\\Component\\HttpKernel\\Kernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))
#20 {main}
"} []

> [2017-07-12 06:38:30] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []

**Comment by nicecp** [comment]
I\`ve resolved my issue, resetting `sql_mode` value

> [mysqld]

> sql_mode=""

Sorry for the bother, and thanks any way :)
