### ISSUE TITLE
$id must be a string, or an Alias object.

### ISSUE THREAD

**Issue by xiaoxing598** [composer/packagist#804]
Whether or not the use of outdated usage, resulting in WEB framework error.

```
Fatal error: Uncaught exception 'Symfony\Component\DependencyInjection\Exception\InvalidArgumentException' with message '$id must be a string, or an Alias object.' in /home/packagist/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ContainerBuilder.php:662 Stack trace: #0 /home/packagist/vendor/symfony/swiftmailer-bundle/DependencyInjection/SwiftmailerExtension.php(274): Symfony\Component\DependencyInjection\ContainerBuilder->setAlias('swiftmailer.mai...', 25) #1 /home/packagist/vendor/symfony/swiftmailer-bundle/DependencyInjection/SwiftmailerExtension.php(118): Symfony\Bundle\SwiftmailerBundle\DependencyInjection\SwiftmailerExtension->configureMailerSpool('default', Array, Object(Symfony\Component\DependencyInjection\ContainerBuilder), 25, true) #2 /home/packagist/vendor/symfony/swiftmailer-bundle/DependencyInjection/SwiftmailerExtension.php(57): Symfony\Bundle\SwiftmailerBundle\DependencyInjection\SwiftmailerExtension->configureMailer('default', Array, Object(Symfony\Component\DependencyInjection\Contain in /home/packagist/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ContainerBuilder.php on line 662
```

**Comment by Seldaek** [comment]
Sorry but no idea what this is about..

**Comment by kahovn** [comment]
hazz

**Comment by kahovn** [comment]
using version 3.3, start the same

**Comment by stof** [comment]
@kahovn the Packagist issue tracker is not a support forum for all packages registered on packagist.org. It is about reporting issues in packagist itself.
